### ISSUE TITLE
Check if URL is valid

### ISSUE THREAD

**Issue by dariru3** [dariru3/gas-birthday_email_reminder#4]
Because the trigger is checking the URL column, if someone  leaves a note in there, add this check should prevent an unintended email

https://www.freecodecamp.org/news/check-if-a-javascript-string-is-a-url/

**Comment by upendrasahni** [comment]
hey @dariru3 can you explain more about this issue?

**Comment by dariru3** [comment]
Hi @upendrasahni . Thanks for asking. 

There's a column for the user to put in a URL, but I saw that the user put in a note instead of valid url. So, I was thinking of updating the code to verify so that the following line doesn't get triggered:

`if(todayFormat.getTime() == birthdayMinus7.getTime() && link){`

**Comment by dariru3** [comment]
Probably use something like this
```js
const isValidUrl = urlString=> {
		let url;
		try { 
	      	url =new URL(urlString); 
	    }
	    catch(e){ 
	      return false; 
	    }
	    return url.protocol === "http:" || url.protocol === "https:";
	}
```
source: https://www.freecodecamp.org/news/check-if-a-javascript-string-is-a-url/
